version: 0.0
os: linux
files:
  - source: /
    destination: /project/admin
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
 #   - location: scripts/clear_cache.sh
 #    timeout: 300
 #    runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_webserver.sh
      timeout: 300
      runas: root
