version: '3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - ./data:/var/lib/mysql
  web:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=myapp
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravelpassword
    volumes:
      - './my-project:/app'
    depends_on:
      - db